apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: dev
  labels:
    app: fastapi-app
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
        env: dev
    spec:
      containers:
        - name: fastapi-app
          image: ghcr.io/vinodkumar88/fastapi-github-actions-demo:dev
          # imagePullPolicy Always ensures k8s always pulls the latest tag
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: APP_ENV
              value: "dev"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
